import { Router } from "express";
import { API_PREFIX } from "@mini-militia/shared";
import { authRouter } from "./auth.routes.js";
import { adminAnalyticsRouter } from "./admin-analytics.routes.js";
import { analyticsRouter } from "./analytics.routes.js";
import { adminStatisticsRouter } from "./admin-statistics.routes.js";
import { healthRouter } from "./health.routes.js";
import { matchRouter } from "./match.routes.js";
import { mvpRouter } from "./mvp.routes.js";
import { playerRouter } from "./player.routes.js";
import { ratingRouter } from "./rating.routes.js";
import { adminRatingRouter } from "./admin-rating.routes.js";
import { userRouter } from "./user.routes.js";
import { statisticsRouter } from "./statistics.routes.js";
import { titleRouter } from "./title.routes.js";
import { adminTitleRouter } from "./admin-title.routes.js";
import { achievementRouter } from "./achievement.routes.js";
import { adminAchievementRouter } from "./admin-achievement.routes.js";
import { rivalryRouter } from "./rivalry.routes.js";
import { adminRivalryRouter } from "./admin-rivalry.routes.js";
import { challengeRouter } from "./challenge.routes.js";
import { adminChallengeRouter } from "./admin-challenge.routes.js";
import { hallOfFameRouter } from "./hall-of-fame.routes.js";
import { adminHallOfFameRouter } from "./admin-hall-of-fame.routes.js";
import { seasonRouter } from "./season.routes.js";
import { adminSeasonRouter } from "./admin-season.routes.js";
import { notificationRouter } from "./notification.routes.js";
import { adminNotificationRouter } from "./admin-notification.routes.js";
import { socialSharingRouter } from "./social-sharing.routes.js";
import { aiInsightRouter } from "./ai-insight.routes.js";
import { adminAIInsightRouter } from "./admin-ai-insight.routes.js";

export const apiRouter = Router();

apiRouter.use(`${API_PREFIX}/health`, healthRouter);
apiRouter.use(`${API_PREFIX}/auth`, authRouter);
apiRouter.use(`${API_PREFIX}/players`, playerRouter);
apiRouter.use(`${API_PREFIX}/matches`, matchRouter);
apiRouter.use(`${API_PREFIX}/users`, userRouter);
apiRouter.use(`${API_PREFIX}/statistics`, statisticsRouter);
apiRouter.use(`${API_PREFIX}/analytics`, analyticsRouter);
apiRouter.use(`${API_PREFIX}/mvp`, mvpRouter);
apiRouter.use(`${API_PREFIX}/ratings`, ratingRouter);
apiRouter.use(`${API_PREFIX}/titles`, titleRouter);
apiRouter.use(`${API_PREFIX}/achievements`, achievementRouter);
apiRouter.use(`${API_PREFIX}/rivalries`, rivalryRouter);
apiRouter.use(`${API_PREFIX}/challenges`, challengeRouter);
apiRouter.use(`${API_PREFIX}/hall-of-fame`, hallOfFameRouter);
apiRouter.use(`${API_PREFIX}/seasons`, seasonRouter);
apiRouter.use(`${API_PREFIX}/notifications`, notificationRouter);
apiRouter.use(`${API_PREFIX}/share`, socialSharingRouter);
apiRouter.use(`${API_PREFIX}/ai`, aiInsightRouter);
apiRouter.use(`${API_PREFIX}/admin/statistics`, adminStatisticsRouter);
apiRouter.use(`${API_PREFIX}/admin/analytics`, adminAnalyticsRouter);
apiRouter.use(`${API_PREFIX}/admin/ratings`, adminRatingRouter);
apiRouter.use(`${API_PREFIX}/admin/titles`, adminTitleRouter);
apiRouter.use(`${API_PREFIX}/admin/achievements`, adminAchievementRouter);
apiRouter.use(`${API_PREFIX}/admin/rivalries`, adminRivalryRouter);
apiRouter.use(`${API_PREFIX}/admin/challenges`, adminChallengeRouter);
apiRouter.use(`${API_PREFIX}/admin/hall-of-fame`, adminHallOfFameRouter);
apiRouter.use(`${API_PREFIX}/admin/seasons`, adminSeasonRouter);
apiRouter.use(`${API_PREFIX}/admin/notifications`, adminNotificationRouter);
apiRouter.use(`${API_PREFIX}/admin/ai`, adminAIInsightRouter);
